<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Getting_Started_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from pandas import Series

In [4]:
#Create a simple series variable
s1=Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [5]:
print(s1.values)

[ 5 10 15 20]


In [6]:
print(s1.index)

RangeIndex(start=0, stop=4, step=1)


In [7]:
print(s1.index.values)

[0 1 2 3]


In [8]:
#Create series from numpy
revenue_array=np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [9]:
revenue_series=Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int64


In [11]:
#Create Series with custom indexes
revenue=Series(revenue_array,index= ["uber","ola","lyft","gojek"])
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int64


In [12]:
revenue['ola']

300

In [13]:
revenue['gojek']

100

In [14]:
#Filter a series based on conditions
print(revenue[revenue>250])

uber    400
ola     300
dtype: int64


In [15]:
#check whether an element is in a series or not
print('ola' in revenue)

True


In [16]:
print('grab' in revenue)

False


In [17]:
#to_dict() function
revenue_dict= revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'lyft': 200, 'gojek': 100}


In [18]:
#Addition of two series
print(revenue+revenue)

uber     800
ola      600
lyft     400
gojek    200
dtype: int64


In [19]:
#Assign names to a series and its index
revenue.name="Company Revenue"
revenue.index.name="Company Name"
print(revenue)

Company Name
uber     400
ola      300
lyft     200
gojek    100
Name: Company Revenue, dtype: int64
