<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Loading_%26_Saving_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#saving single array
np.save("saved_array",arr)

In [4]:
#loading single array
load_Array1= np.load("saved_array.npy")
print(load_Array1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#saving multiple array
arr2=np.arange(25)
arr3=np.arange(5)
np.savez("saved_archive.npz",x=arr2,y=arr3)

In [7]:
#loading multiple array
load_npz=np.load("saved_archive.npz")
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [9]:
#saving array to text file
np.savetxt("my_array.txt",arr2,delimiter=",")

In [10]:
#loading array from text file
load_file=np.loadtxt("my_array.txt",delimiter=",")
print(load_file)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]
