In [ ]:
import numpy as np

In [ ]:
#Creating 1-D numpy array
mylist1=[101,102,103]
myArray=np.array(mylist1)
print(myArray)

[101 102 103]


In [ ]:
#creating 2D numpy array
mylist2=[201,202,203]
myArray2D=np.array([mylist1,mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [ ]:
#Finding dimensions of array - shape
print("myArray Dimensions")
print(myArray.shape)
print("myArray2D Dimensions")
print(myArray2D.shape)

myArray Dimensions
(3,)
myArray2D Dimensions
(2, 3)


In [ ]:
#Finding Datatype of array - dtype
print("myArray Datatype")
print(myArray.dtype)
print("myArray2D Datatype")
print(myArray2D.dtype)

myArray Datatype
int64
myArray2D Datatype
int64


In [ ]:
#Array creation and Initialization Functions - zeros
zero_array=np.zeros(5)
print(zero_array)
zero_array2D=np.zeros([5,5])
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Array creation and Initialization Functions - ones
print("1D")
one_array=np.ones(5)
print(one_array)
print("2D")
one_array2D=np.ones([5,5])
print(one_array2D)

1D
[1. 1. 1. 1. 1.]
2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Array creation and Initialization function - empty
print("1D")
empty_array=np.empty(5)
print(empty_array)
print("2D")
empty_array2D=np.empty([5,5])
print(empty_array2D)

1D
[1. 1. 1. 1. 1.]
2D
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Array creation and initialization function - eye
Identity_Array=np.eye(3)
print(Identity_Array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Array creation and initialization function - arange
AP_array= np.arange(0,50,2)
print(AP_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
