<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Numpy_Array_Indexes_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr= np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [ ]:
#Access individual array elements
print("First Element")
print(arr[0])
print("Second Element")
print(arr[1])
print("Third Element")
print(arr[2])
print("Fifth Element")
print(arr[4])

First Element
100
Second Element
102
Third Element
104
Fifth Element
108


In [ ]:
#Slicing of array Indexes arr[start:stop:step]
print(arr[0:5:1])

[100 102 104 106 108]


In [ ]:
#Updating array using slices
arr[0:5]=0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [ ]:
#Interesting point about slicing-Memory-allocation -view vs copy
arr2=arr[4:10]
print(arr2)
arr2[:]=1
print(arr2)

[  0 110 112 114 116 118]
[1 1 1 1 1 1]


In [ ]:
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [ ]:
#copy() function=> creating new numpy memory for array
arr3=arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [ ]:
arr3[:]=0
print(arr3)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
