<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Numpy_array_indexes_Part_2_Multidimensional_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Accessing rows
print(arr2d[0])
print(arr2d[1])

[1 2 3]
[4 5 6]


In [4]:
#Accessing elements of array
print(arr2d[0][0])

1


In [5]:
print(arr2d[1][2])

6


In [6]:
#slicing in 2D arrays
slice1= arr2d[0:1,0:2]
print(slice1)

[[1 2]]


In [7]:
slice2=arr2d[0:2,0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [8]:
slice3=arr2d[:2,:3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [9]:
slice4=arr2d[1:,2:]
print(slice4)

[[6]
 [9]]


In [10]:
#using loops to change index
arr_len=arr2d.shape
print(arr_len)

(3, 3)


In [11]:
nrows=arr_len[0]
print(nrows)

3


In [12]:
for i in range(nrows):
  arr2d[i][0]=i
print(arr2d)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [13]:
#Accessing rows using list of index values
print(arr2d[[0,1]])

[[0 2 3]
 [1 5 6]]


In [14]:
print(arr2d[[1,0]])

[[1 5 6]
 [0 2 3]]
