<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Premium_Array_Operations_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#Function of numpy arrays-arange()
A= np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
B= np.arange(5,10)
print(B)

[5 6 7 8 9]


In [4]:
C= np.arange(5,10,2)
print(C)

[5 7 9]


In [6]:
#Function of numpy array-sqrt()
D=np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [7]:
#Function of numpy array-exp()
E=np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [8]:
#Function of numpy array-random()
F= np.random.randn(5)
print(F)

[-0.81488066  1.29775621 -0.02124521  0.37833017 -0.70925193]


In [9]:
F=np.random.randn(5,5)
print(F)

[[-1.19385428  1.04421319 -0.42594597  1.12013059  1.12630655]
 [ 1.21847488  0.37890403  1.54906256  0.95429414  0.23559889]
 [ 0.18206554  0.45883032 -1.27524588 -0.6566868  -1.74822876]
 [-0.78600143  1.34689551  1.0408503  -0.28954098  0.20398938]
 [-0.76402013 -2.4507369   0.25798243  0.37529557 -1.0509706 ]]


In [10]:
#Function of numpy arrays-add()
G= np.add(A,D)
print(G)

[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [11]:
#Function of numpy arrays- maximum()
A= np.array([1,5,7,10])
B= np.array([0,6,8,9])
H= np.maximum(A,B)
print(H)

[ 1  6  8 10]
