<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Python-Data-Analysis-and-Visualization-Bootcamp/blob/main/Scalar_Operations_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Scalar array multiplication - using * operator
arr1=np.array([[1,2,3],[5,6,7]])
print(arr1)

[[1 2 3]
 [5 6 7]]


In [ ]:
arr2= arr1*arr1
print(arr2)

[[ 1  4  9]
 [25 36 49]]


In [ ]:
#Exponential multiplication - using ** operator
arr3= arr1 ** 3
print(arr3)

[[  1   8  27]
 [125 216 343]]


In [ ]:
#Scalar subtraction of array elements
arr4= arr3-arr1
print(arr4)

[[  0   6  24]
 [120 210 336]]


In [ ]:
#scalar Division of array elements
arr5= 1/arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.2        0.16666667 0.14285714]]
